### ISSUE TITLE
小白求助：编译go项目不成功

### ISSUE THREAD

**Issue by RobertHoffman** [code-innovator-zyx/wechat-gptbot#13]
github上有许多微信机器人的项目，由于微信不断升级，过去的项目很多都不能使用了。而您的项目看起来很好用，为您的分享精神点赞！
我是编程小白，只会写python。我现在使用一台window电脑，使用cygwin64终端运行您的makefile文件。在解决了前序问题后，运行下列代码时：
> fi
	@# 编译 Go 项目
	@if go build .; then \
		echo "项目构建成功"; \
	else \
		echo "项目构建失败，请检查错误信息"; \
		exit 1; \

出现了没法展开的报错：
> runtime/cgo
runtime/cgo: C:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2
项目构建失败，请检查错误信息
make: *** [makefile:35: local] Error 1

我电脑上安装了python、go，并且都有环境变量，请问我应该如何找到报错信息，或者直接解决问题呢，非常感谢您。

**Comment by code-innovator-zyx** [comment]
> cygwin64

你这个一眼看上去应该就是电脑缺少C编译器，项目底层有cgo代码，需要安装c编译器，可以运行 `gcc --version`,看看是否缺少C环境，如果没有正确打印版本号， windows 推荐下载安装   [MinGW]("http://www.mingw.org/") ,安装的时候选择gcc编译器

**Comment by code-innovator-zyx** [comment]
> MinGW

安装地址  http://www.mingw.org/

**Comment by RobertHoffman** [comment]
经过一些尝试，虽然下载了MinGW也不能使用make指令，但我已经成功编译了go项目。现在我在cmd中输入wechat-gptbot时，能够成功进入界面，但是它让我输入登录密码，我不知道这是什么意思，因此继续向您求助。
![微信图片编辑_20240708154218](https://github.com/code-innovator-zyx/wechat-gptbot/assets/43536186/d9a3b37a-5829-457d-894b-b83e45f9c692)
![微信截图_20240708154326](https://github.com/code-innovator-zyx/wechat-gptbot/assets/43536186/23e29a2a-98fa-4db4-aa6d-88156789452c)

**Comment by code-innovator-zyx** [comment]
![image](https://github.com/code-innovator-zyx/wechat-gptbot/assets/124665918/8b6d127b-c331-45c8-888f-5ed8c8bd2ecc)
初始账号密码  admin   admin777   ，这是新加的管理页面权限控制，因为不加登录页公网访问任何人都能修改数据，所以加了一个登录的更安全
