### ISSUE TITLE
使用docker部署后，访问8501前端登录界面，默认的登录密码应该从哪里获取？

### ISSUE THREAD

**Issue by 1783cwf** [code-innovator-zyx/wechat-gptbot#18]
<img width="1689" alt="image" src="https://github.com/user-attachments/assets/849bbf2b-c51b-457c-9cd0-45cc132ff9ac">

**Comment by code-innovator-zyx** [comment]
> <img alt="image" width="1689" src="https://private-user-images.githubusercontent.com/56056304/368109331-849bbf2b-c51b-457c-9cd0-45cc132ff9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjU1MTAsIm5iZiI6MTcyNjYyNTIxMCwicGF0aCI6Ii81NjA1NjMwNC8zNjgxMDkzMzEtODQ5YmJmMmItYzUxYi00NTdjLTljZDAtNDVjYzEzMmZmOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAyMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNWZhODI2MDY2ODQ5YjE3YzhlZmEwNzI0NTg1NzUyYmE5MTEyZWYyNmQ1OWQ0ZWFhZTVhNDRhZmZkMDI4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mhXLGD3IWvmuso8rxHHflMafJ4gio9_krQvmlsiaCTI">

.streamlit 文件夹下有个默认的账号密码

**Comment by 1783cwf** [comment]
好的
