### ISSUE TITLE
关于代码借鉴的说明与请求

### ISSUE THREAD

**Issue by HenryXiaoYang** [code-innovator-zyx/wechat-gptbot#20]
您好！我是[XYBot](https://github.com/HenryXiaoYang/XYBot)的开发者，我在您的项目中发现自己写的代码被借鉴。主要在天气插件与新闻插件上，您项目中的天气插件输出格式与我项目中的天气信息输出格式一摸一样。同时，新闻插件的输出格式也大差不差。我[项目](https://github.com/HenryXiaoYang/XYBot)的开源协议是[GPL-3.0 license](https://github.com/HenryXiaoYang/XYBot?tab=GPL-3.0-1-ov-file#)，因此请表明一下，谢谢！

**Comment by the-yex** [comment]
> 您好！我是[XYBot](https://github.com/HenryXiaoYang/XYBot)的开发者，我在您的项目中发现自己写的代码被借鉴。主要在天气插件与新闻插件上，您项目中的天气插件输出格式与我项目中的天气信息输出格式一摸一样。同时，新闻插件的输出格式也大差不差。我[项目](https://github.com/HenryXiaoYang/XYBot)的开源协议是[GPL-3.0 license](https://github.com/HenryXiaoYang/XYBot?tab=GPL-3.0-1-ov-file#)，因此请表明一下，谢谢！

我看了一下，格式确实有相似之处，但是我确信没有见过你这个开源项目，而且这是前两年写的，我回去看了一下代码，格式化也不是在项目里，这里的天气数据是调用三方api返回的数据，格式化好了的；所以我这里的代码没有任何借鉴的地方，新闻是借鉴天气api生成的数据统一返回的

**Comment by the-yex** [comment]
> 您好！我是[XYBot](https://github.com/HenryXiaoYang/XYBot)的开发者，我在您的项目中发现自己写的代码被借鉴。主要在天气插件与新闻插件上，您项目中的天气插件输出格式与我项目中的天气信息输出格式一摸一样。同时，新闻插件的输出格式也大差不差。我[项目](https://github.com/HenryXiaoYang/XYBot)的开源协议是[GPL-3.0 license](https://github.com/HenryXiaoYang/XYBot?tab=GPL-3.0-1-ov-file#)，因此请表明一下，谢谢！

<img width="976" alt="image" src="https://github.com/user-attachments/assets/eb550484-d304-4183-affd-ceec42859e8b">
天气是这样来的，这里借鉴了什么😂

**Comment by HenryXiaoYang** [comment]
好的谢谢，发一下api来源吧😂😂逛github看到自己项目的东西被照搬属实吓了一跳😂😂
