### ISSUE TITLE
登陆以后回复报错了

### ISSUE THREAD

**Issue by akidaa-me** [code-innovator-zyx/wechat-gptbot#6]
1     【🤖】:1
2     抱歉，出错了，请稍后重试~
3     【🤖】:6
4     抱歉，出错了，请稍后重试~
5     【🤖】:
=====🤖=======
{"func":"wechat-gptbot/core/gpt.(*openAiClient)/openai.go:(75)","level":"info","msg":"openAIClient.CreateChatCompletion err=invalid character '<' looking for beginning of value\n","timestamp":"2024-05-22 12:08:58"}
[text] Response: 抱歉，出错了，请稍后重试~

**Comment by code-innovator-zyx** [comment]
> 1 【🤖】:1 2 抱歉，出错了，请稍后重试~ 3 【🤖】:6 4 抱歉，出错了，请稍后重试~ 5 【🤖】: =====🤖======= {"func":"wechat-gptbot/core/gpt.(*openAiClient)/openai.go:(75)","level":"info","msg":"openAIClient.CreateChatCompletion err=invalid character '<' looking for beginning of value\n","timestamp":"2024-05-22 12:08:58"} [text] Response: 抱歉，出错了，请稍后重试~

你是用的openapi 吧，设置代理了吗

**Comment by akidaa-me** [comment]
我是openwrt做网关，在Ubuntu图形界面浏览器里可以正常访问谷歌，代理链接没填，是需要修改DEFAULT_OPENAI_URL = https://api.v3.cm吗

**Comment by code-innovator-zyx** [comment]
> 我是openwrt做网关，在Ubuntu图形界面浏览器里可以正常访问谷歌，代理链接没填，是需要修改DEFAULT_OPENAI_URL = [https://api.v3.cm吗](https://api.v3.cm%E5%90%97)

是的，如果不修改默认走openai的地址，这个需要配置代理；如果不配代理，就要修改 DEFAULT_OPENAI_URL
